const intro=document.getElementById('intro'),quiz=document.getElementById('quiz'),analysis=document.getElementById('analysis'),results=document.getElementById('results'),stepCard=document.getElementById('stepCard'),stepTxt=document.getElementById('stepTxt'),bar=document.getElementById('bar'),summary=document.getElementById('summary'),resultIntro=document.getElementById('resultIntro'),cards=document.getElementById('cards'),todo1=document.getElementById('todo1');
const state={district:'小和田',end:19,budget:20000,meal:'できれば',privateOk:true};let step=0,lastPlans=[];
const districts=[...new Set(facilities.flatMap(f=>String(f.district).split('・')))].sort((a,b)=>a.localeCompare(b,'ja'));
function formatTime(v){return `${Math.floor(v)}:${v%1?'30':'00'}`}function money(v){return v>0?`${v.toLocaleString()}円前後`:'要確認'}
function startQuiz(){intro.classList.add('hidden');results.classList.add('hidden');quiz.classList.remove('hidden');step=0;render();scrollTo(0,0)}
function showSample(){state.district='小和田';state.end=19;state.budget=20000;state.meal='できれば';state.privateOk=true;intro.classList.add('hidden');diagnose(true)}
const questions=[
()=>`<div class="qnum">1 / 5</div><h2>お子さんの小学校区を選んでください</h2><div class="help">まずは対象学区に含まれる施設だけに絞ります。</div><select class="select" id="district">${districts.map(d=>`<option value="${d}">${d}小学校区</option>`).join('')}</select><div class="nav"><button class="nextBtn" onclick="saveDistrict()">次へ</button></div>`,
()=>`<div class="qnum">2 / 5</div><h2>何時ごろまで預かりが必要ですか？</h2><div class="help">仕事の終了時刻ではなく、実際にお迎えへ到着できる時刻で選んでください。</div><div class="choices">${[18,18.5,19,19.5,20].map(v=>`<button class="choice ${state.end===v?'active':''}" onclick="state.end=${v};render()">${formatTime(v)}</button>`).join('')}</div><div class="nav"><button class="backBtn" onclick="back()">戻る</button><button class="nextBtn" onclick="next()">次へ</button></div>`,
()=>`<div class="qnum">3 / 5</div><h2>通常月の予算上限はどのくらいですか？</h2><div class="help">延長料金や長期休暇の追加料金は別として、まず毎月の固定費で比べます。</div><div class="money"><strong id="budgetVal">${state.budget.toLocaleString()}</strong><span>円 / 月</span></div><input class="range" type="range" min="12000" max="35000" step="1000" value="${state.budget}" oninput="state.budget=+this.value;budgetVal.textContent=state.budget.toLocaleString()"><div class="nav"><button class="backBtn" onclick="back()">戻る</button><button class="nextBtn" onclick="next()">次へ</button></div>`,
()=>`<div class="qnum">4 / 5</div><h2>夏休みの昼食対応は重視しますか？</h2><div class="help">毎日のお弁当負担を減らしたい場合は、ここで希望を反映します。</div><div class="choices">${['必須','できれば','不要'].map(v=>`<button class="choice ${state.meal===v?'active':''}" onclick="state.meal='${v}';render()">${v}</button>`).join('')}</div><div class="nav"><button class="backBtn" onclick="back()">戻る</button><button class="nextBtn" onclick="next()">次へ</button></div>`,
()=>`<div class="qnum">5 / 5</div><h2>民設の学童も候補に入れますか？</h2><div class="help">公設だけに絞るか、民設も含めて選択肢を広げるかを選びます。</div><div class="choices"><button class="choice ${state.privateOk?'active':''}" onclick="state.privateOk=true;render()">民設も含める</button><button class="choice ${!state.privateOk?'active':''}" onclick="state.privateOk=false;render()">公設のみ</button></div><div class="nav"><button class="backBtn" onclick="back()">戻る</button><button class="nextBtn" onclick="diagnose()">候補を見る</button></div>`
];
function render(){stepCard.innerHTML=questions[step]();if(step===0)district.value=state.district;stepTxt.textContent=`${step+1} / 5`;bar.style.width=((step+1)*20)+'%'}
function saveDistrict(){state.district=district.value;next()}function next(){if(step<4)step++;render()}function back(){if(step>0)step--;render()}
function fit(f){const ds=String(f.district).split('・');if(!ds.includes(state.district))return null;if(!state.privateOk&&f.type==='民設')return null;let score=50,confidence=100,flags=[],positives=[],cautions=[];
 if(f.maxEnd>0){if(f.maxEnd<state.end)return null;score+=25;positives.push(`${formatTime(f.maxEnd)}まで利用可`)}else{score+=7;confidence-=35;flags.push('時間');cautions.push('終了時刻は要確認')}
 if(f.monthlyFee>0){if(f.monthlyFee<=state.budget){score+=15;positives.push('通常月は予算内')}else{score-=16;flags.push('予算');cautions.push(`通常月の目安が予算を${(f.monthlyFee-state.budget).toLocaleString()}円超えます`)}}else{score+=5;confidence-=30;flags.push('料金');cautions.push('月額料金は要確認')}
 if(state.meal==='不要'){score+=8}else if(f.meal==='あり'){score+=10;positives.push('長期休暇の昼食対応あり')}else{score+=state.meal==='できれば'?4:-5;confidence-=15;flags.push('昼食');cautions.push('長期休暇の昼食対応は要確認')}
 if(String(f.status2027).includes('要更新')){confidence-=10;cautions.push('2027年度の募集情報は更新待ち')}
 return {...f,score:Math.max(1,Math.min(100,score)),confidence:Math.max(20,Math.min(100,confidence)),flags,positives,cautions}}
function pool(){return facilities.map(f=>fit(f)).filter(Boolean)}
function choose(list){if(!list.length)return[];const used=new Set(),out=[];const first=[...list].sort((a,b)=>b.score-a.score||b.confidence-a.confidence)[0];out.push({...first,role:'第一候補',roleText:'条件のバランスがよい'});used.add(first.name);const second=[...list].filter(x=>!used.has(x.name)&&x.monthlyFee>0&&x.monthlyFee<=state.budget).sort((a,b)=>a.monthlyFee-b.monthlyFee||b.score-a.score)[0]||[...list].filter(x=>!used.has(x.name)).sort((a,b)=>b.score-a.score)[0];if(second){out.push({...second,role:'比較候補',roleText:'費用も含めて比較しやすい'});used.add(second.name)}const third=[...list].filter(x=>!used.has(x.name)).sort((a,b)=>b.confidence-a.confidence||b.score-a.score)[0];if(third)out.push({...third,role:'予備候補',roleText:'もしもの時に確認しておきたい'});return out}
function diagnose(sample=false){quiz.classList.add('hidden');intro.classList.add('hidden');results.classList.add('hidden');analysis.classList.remove('hidden');setTimeout(showResults,sample?300:550)}
function showResults(){const list=pool(),plans=choose(list);lastPlans=plans;analysis.classList.add('hidden');results.classList.remove('hidden');summary.innerHTML=`<b>${state.district}小学校区</b> ／ ${formatTime(state.end)}まで ／ 月${state.budget.toLocaleString()}円以内 ／ 昼食：${state.meal} ／ ${state.privateOk?'民設も含める':'公設のみ'}`;resultIntro.innerHTML=list.length?`条件上、まず確認したい施設が<strong>${list.length}施設</strong>残りました。その中から、役割の違う3候補を整理しています。数字だけで決めず、見学や問い合わせの順番を決めるために使ってください。`:`今の条件では、成立する候補を確認できませんでした。必要時刻や民設の可否を見直す必要があります。`;cards.innerHTML=plans.length?plans.map((f,i)=>card(f,i)).join(''):`<div class="planCard"><h3>条件に合う候補が見つかりませんでした</h3><p>必要な利用終了時刻を早める、民設も含める、予算を見直すなど、家庭側の条件を変えて再度確認してください。</p></div>`;todo1.textContent=plans[0]?`${plans[0].name}の2027年度募集情報と見学方法を確認する`:'勤務・送迎条件を見直して再診断する';scrollTo({top:0,behavior:'smooth'})}
function card(f,i){const time=f.maxEnd>0?`○ ${formatTime(f.maxEnd)}まで利用可`:'要確認：利用終了時刻';const fee=f.monthlyFee>0?(f.monthlyFee<=state.budget?`○ ${money(f.monthlyFee)}`:`予算超過：${money(f.monthlyFee)}`):'要確認：月額料金';const meal=f.meal==='あり'?'○ 昼食対応あり':'要確認：長期休暇の昼食';const next=f.flags.includes('料金')?'料金と2027年度の募集方法を問い合わせる':f.flags.includes('昼食')?'長期休暇の昼食対応と募集日程を確認する':'2027年度の見学・募集日程を確認する';return `<article class="planCard ${i===0?'primaryPlan':''}"><div class="planLabel">${f.role}｜${f.roleText}</div><h3>${f.name}</h3><div class="meta">${f.type} ・ ${f.operator}</div><div class="details"><div class="detail"><b>対象学区</b><span>○ ${state.district}小学校区</span></div><div class="detail"><b>利用時間</b><span>${time}</span></div><div class="detail"><b>通常月費用</b><span>${fee}</span></div><div class="detail"><b>夏休み昼食</b><span>${meal}</span></div></div><div class="reason"><b>まず確認すること</b><br>${next}</div><a class="linkBtn" href="${f.source}" target="_blank" rel="noopener">公式情報を見る →</a></article>`}
function restart(){results.classList.add('hidden');intro.classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function copyResult(){let t=`【学童Plan B｜茅ヶ崎】\n${state.district}小学校区 / ${formatTime(state.end)}まで / 月${state.budget.toLocaleString()}円以内\n`;lastPlans.forEach(p=>t+=`\n${p.role}：${p.name}`);t+='\n\n※申込前に必ず最新の公式情報をご確認ください。';navigator.clipboard?.writeText(t);alert('結果をコピーしました')}